# Metrowest machine learning self-driving car
#### The project is a self-driving car.  Refer to the .pdf document for details
#### This notebook trains the the CNN.
#### References:
#### https://www.meetup.com/Natick-Artificial-Intelligence-Meetup/
#### https://github.com/experiencor.self-driving-toy-car/
#### http://vision.stanford.edu/teaching/cs231n/
#### https://www.tensorflow.org/

In [5]:
import cv2
import time
import numpy as np
import os, random
import keras.utils.vis_utils as vutil
from IPython.display import SVG
import tensorflow as tf
import keras.models as models
from keras.optimizers import SGD
from imgaug import augmenters as iaa
from keras.layers.core import Dense, Dropout, Activation, Flatten, Reshape
from keras.layers.convolutional import MaxPooling2D, UpSampling2D, Conv2D
from keras.utils import np_utils
from keras.layers import GlobalAveragePooling2D, Input
from keras.models import Model
from keras.layers import Input, Dense
from keras.callbacks import TensorBoard, EarlyStopping, ModelCheckpoint
from keras import backend as K
import numpy as np
import matplotlib.pyplot as plt
from keras.applications.vgg16 import preprocess_input
import matplotlib.animation as animation
import sys

import sys
sys.path.append('../lib')
from metrowestcar_image_params import IParams


%matplotlib nbagg

FRAME_H = IParams.height
FRAME_W = IParams.width

print("done")

done


In [8]:
# augmentation (future)
def augment(image, steer):
    return image, steer

## Data Loading and Preprocessing

In [1]:
# Load the raw data.
import sys
sys.path.append('../lib')

from metrowestcar_file_io import FileReader
file_reader = FileReader()

dir_list = [
    "../data/pictures_test",
]

image_array = file_reader.read_images_from_list_of_directories(dir_list)
steering_array = file_reader.read_steering_from_list_of_directories(dir_list)

print(image_array.shape)   
print(steering_array.shape)

loading from ../data/pictures_test
loading from ../data/pictures_test
(11, 480, 640, 3)
(11,)


In [51]:
full_data = np.vstack((steering_array, image_array))
print(full_data.shape)

#aa = np.vstack((a,a))
#print(aa)


ValueError: all the input arrays must have same number of dimensions

In [39]:
# Shuffle the data
# if shuffle: np.random.shuffle(self.images)
import numpy as np
        
arr = np.array([
    [0, 1],
    [2 ,3],
    [4, 5],
    [6, 7],
    [8, 9],
])
print(arr.shape)
print(arr)
print(  arr[:][0], arr[:][1]  )

#foo = np.array([[11],[12],[13],[14],[15]])
#print(foo)
#
#bar = np.stack(foo, foo)
#
#print(bar)

#arr = arr[np.newaxis]
#print(arr)

#            image = image[np.newaxis]
#            my_images = np.append(my_images, image, axis=0)
        
        
#np.random.shuffle(arr)
#print(arr)

#foo = np.random.shuffle(np.array(range(5)))
#print(foo)

#arr = np.array([image_array, steering_array])
        

(5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1] [2 3]


In [49]:
a = np.array((1,2,3))
aa = np.vstack((a,a))
print(aa)

b = np.array((2,3,4))
print(np.vstack((aa,b)))

#print
#a = np.array([[1],[2],[3]])
#b = np.array([[2],[3],[4]])
#print(np.hstack((a,b)))


[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]
 [2 3 4]]


In [41]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.stack(a, b))


TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
# Visualize some examples from the dataset.
from metrowestcar_display import Displayer





In [ ]:
# Split the data into train, val, and test sets. In addition we will
# create a small development set as a subset of the training data;
# we can use this for development so our code runs faster.

In [ ]:
# Preprocessing

## Construct the Model (CNN Classifier)

Code for this section is in **lib/model_cnn.py**.

In [10]:
# Construct the network
image_inp = Input(shape=(FRAME_H, FRAME_W, 3))

x = Conv2D(filters=16, kernel_size=(3, 5), activation='relu', padding='valid')(image_inp)
x = Conv2D(filters=16, kernel_size=(3, 5), activation='relu', padding='valid')(x)
x = MaxPooling2D((4, 2))(x)

x = Conv2D(filters=32, kernel_size=(3, 5), activation='relu', padding='valid')(x)
x = Conv2D(filters=32, kernel_size=(3, 5), activation='relu', padding='valid')(x)
x = MaxPooling2D((4, 2))(x)

x = Conv2D(filters=4,  kernel_size=(1, 1), activation='linear', padding='same')(x)

x = Flatten()(x)

x = Dense(1, activation='tanh', kernel_regularizer='l1')(x)

angle_out = x

model = Model(inputs=[image_inp], outputs=[angle_out])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 480, 640, 3)       0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 478, 636, 16)      736       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 476, 632, 16)      3856      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 119, 316, 16)      0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 117, 312, 32)      7712      
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 115, 308, 32)      15392     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 28, 154, 32)       0         
__________

# Train the model

In [ ]:
# Save model weights to file
model.save_weights('../network/weights.hdf5')
model.load_weights('../network/weights.hdf5')

In [ ]:
# Plot loss as a function of iteration number

# Run the model and evaluate performance

In [ ]:
# Evaluate performance on training and validation set
y_train_pred = svm.predict(X_train)
print('training accuracy: %f' % (np.mean(y_train == y_train_pred), ))
y_val_pred = svm.predict(X_val)
print('validation accuracy: %f' % (np.mean(y_val == y_val_pred), ))

# other stuff...

In [ ]:
early_stop  = EarlyStopping(monitor='val_loss', min_delta=0.001, patience=2, mode='min', verbose=1)
checkpoint  = ModelCheckpoint('weights.hdf5', monitor='val_loss', verbose=1, save_best_only=True, mode='min', period=1)

batch_num = 32
session_t = ['../network/drive_trial_0', '../network/drive_trial_2']
session_v = ['../network/drive_trial_1', '../network/drive_trial_3']

gen_train = BatchGenerator(session_t, batch_num)
gen_valid = BatchGenerator(session_v, batch_num, jitter = False)

num_train = gen_train.get_size()/batch_num
num_valid = gen_valid.get_size()/batch_num

In [ ]:
def custom_loss(y_true, y_pred):
    #y_true = tf.Print(y_true, [tf.reduce_mean(y_true - y_pred)], message='DEBUG', summarize=10000) 
    
    # custom loss 1
    #y_pred = tf.clip_by_value(y_pred, -1+1e-7, 1-1e-7)
    #loss = -((1. - y_true) * tf.log(1. - y_pred) + (1. + y_true) * tf.log(1. + y_pred))
    #loss = tf.reduce_mean(loss)
    
    # custom loss 2
    loss = tf.square(y_true - y_pred)
    loss = .5 * tf.reduce_mean(loss)
    
    # custom loss 3
    #loss = tf.abs(y_true - y_pred)
    #loss = tf.reduce_mean(loss)
    
    return loss

In [ ]:
import os

print(os.getcwd())
print(os.listdir('../logs/'))


tb_counter  = max([int(num) for num in os.listdir('../logs/')]) + 1
tensorboard = TensorBoard(log_dir='../logs/' + str(tb_counter), histogram_freq=0, write_graph=True, write_images=False)

minimizer = SGD(lr=0.0001)

#model.compile(loss=custom_loss, optimizer=minimizer)
model.compile(loss=custom_loss, optimizer='adam')

model.fit_generator(generator = gen_train.get_gen(),
                    steps_per_epoch = num_train, 
                    epochs  = 3, 
                    verbose = 1,
                    validation_data = gen_valid.get_gen(), 
                    validation_steps = num_valid, 
                    callbacks = [early_stop, checkpoint, tensorboard], 
                    max_q_size = 3)